2fa/registration frontend
ibks-bank/frontend pull request #1
Opened 2022-03-15 18:23 UTC by ujuzy

2022-03-15 19:55 UTC, ujuzy commented on src/ConfirmPage/ConfirmPage.jsx
> +        //if (username && password) {
убери все ненужные комменты

2022-03-15 19:57 UTC, ujuzy commented on src/RegisterPage/RegisterPage.jsx
> +    render() {
на странице регистрации все формы подписаны не по-человечески (какой-то всратый кэмелкейс и тд). сделай нормально

2022-03-15 19:58 UTC, ujuzy commented on src/RegisterPage/RegisterPage.jsx
> +    render() {
еще бы дату выбирать в календаре, а не вручную вводить (а то хз в каком виде ее вообще вводить)

2022-03-15 19:59 UTC, ujuzy commented on src/RegisterPage/RegisterPage.jsx
> +    render() {
добавить подтверждение пароля (когда два раза надо ввести) + кнопку, по которой можно отобразить пароль (сейчас всегда скрытый)

2022-03-15 20:00 UTC, ujuzy commented on src/RegisterPage/RegisterPage.jsx
> +    render() {
Добавить проверку на стойкость пароля (тип чтобы обязательно содержал буквы, цифры, спец символы и тд)

2022-03-15 20:02 UTC, ujuzy commented
добавить после логина страницу с отображением паспортных данных, просто чтобы можно было удостовериться, что мы залогинились (ручка `/v1/passport`)

2022-03-15 20:45 UTC, ujuzy commented on src/_helpers/auth-header.js
> +        return { 'Authorization': 'Bearer ' + user.token };
у нас токен через `X-Auth-Token` передается. `Bearer ` тоже не надо

2022-03-16 05:25 UTC, sofiton commented on src/_helpers/auth-header.js
> +        return { 'Authorization': 'Bearer ' + user.token };
не используется
было ранее для теста
сейчас остается для заглушки
убирать буду потом

2022-03-16 11:29 UTC, LaNdErTiS commented on .idea/.gitignore
> +# Default ignored files
.idea/ директории не должно быть в репозитории

2022-03-16 11:48 UTC, LaNdErTiS commented on src/RegisterPage/RegisterPage.jsx
> +        //this.setState({confirmPass: {...confirmPass, [name]:value}})
```suggestion
```

2022-03-16 11:48 UTC, LaNdErTiS commented on src/RegisterPage/RegisterPage.jsx
> +    //}
```suggestion
```

2022-03-16 11:48 UTC, LaNdErTiS commented on src/RegisterPage/RegisterPage.jsx
> +        //else {return;}
```suggestion
```

2022-03-16 11:48 UTC, LaNdErTiS commented on src/_services/user.service.js
> +//            return user;
```suggestion
```

2022-03-16 11:48 UTC, LaNdErTiS commented on src/_services/user.service.js
> +//
```suggestion
```

2022-03-16 11:48 UTC, LaNdErTiS commented on src/protos/profile.proto
> +//import "protoc-gen-openapiv2/options/annotations.proto";
```suggestion
```

2022-03-16 12:03 UTC, LaNdErTiS requested changes

2022-03-16 12:03 UTC, LaNdErTiS commented on package.json
> +      "last 1 chrome version",
По поводу браузеров, предлагаю ограничиться только хромом, на крайний случай еще мозиллу можно добавить.
С сафари будут траблы, так как для этого потребуется мак, чтобы была возможность инсталляция драйвера в системе для возможности тестить это + меньше запары, так как что-то может оказаться специфичным для сафари. Что скажите? @ujuzy @sofiton

2022-03-16 12:10 UTC, sofiton commented on package.json
> +      "last 1 chrome version",
@LaNdErTiS у меня мака нет это проверять + реально нужно специфичное апи. конечно можно и над сафари думать, но думаю, можно убрать

2022-03-16 12:29 UTC, LaNdErTiS commented on package.json
> +      "last 1 chrome version",
@sofiton в рамках ТЗ считаю можно его опустить

2022-03-16 14:31 UTC, ujuzy commented on package.json
> +      "last 1 chrome version",
сыглы

2022-03-16 14:59 UTC, ujuzy commented on src/RegisterPage/RegisterPage.jsx
> +    render() {
кстати по поводу дат: обрати внимание, как они выглядят в сваггере, грпц не пропустит рандомный формат

2022-04-10 11:37 UTC, merged